#!/usr/bin/env zsh
##----------------------------------------------------------------------------------------
##--     file: ${XDG_CONFIG_HOME}/dotfiles/i3/blocks/battery                            --
##--      vim: set rnu nu ai et ts=4 sw=4 ft=zsh syn=zsh :                              --
##-- requires: acpi pango                                                               --
##----------------------------------------------------------------------------------------
##-- BOF

##-- draw the blocklet -------------------------------------------------------------------
##----------------------------------------------------------------------------------------
##-- variables
ac=`/usr/bin/acpi -a | /usr/bin/grep -o 'on'`
bat_c=`/usr/bin/acpi -b | /usr/bin/wc -l`
bat_0=`/usr/bin/acpi -b | /usr/bin/awk 'FNR==1 {print $4}' | /usr/bin/sed 's|[^0-9]||g'`
if [[ ${bat_c} -gt '1' ]]; then
    bat_1=`/usr/bin/acpi -b | /usr/bin/awk 'FNR==2 {print $4}' | /usr/bin/sed 's|[^0-9]||g'`
    bat_avg=$(((bat_0 + bat_1)/2.0))
else
    bat_avg=$bat_0
fi

##-- colours
bg0="#000000"
if [[ $ac == 'on' ]]; then
    bi="  "
    fg0="#26cece"
    elif [[ $ac != 'on' && $bat_a -ge '80' ]]; then
        bi="  "
        fg0="#19cf08"
    elif [[ $ac != 'on' && $bat_a -ge '60' ]]; then
        bi="  "
        fg0="#19cf08"
    elif [[ $ac != 'on' && $bat_a -ge '40' ]]; then
        bi="  "
        fg0="#e65c00"
    elif [[ $ac != 'on' && $bat_a -ge '20' ]]; then
        bi="  "
        fg0="#e62e00"
    elif [[ $ac != 'on' && $bat_a -lt '20' ]]; then
        bi="  "
        fg0="#d91c07"
fi
fg1="#aaaaaa"

##-- full_text && short_text
ft="<span foreground='$fg0' background='$bg0'> ${bi} </span>"
ft+="<span foreground='$fg1' background='$bg0'> ${bat_0} </span>"
if [[ ${bat_c} -gt '1' ]]; then
    ft+="<span foreground='$fg1' background='$bg0'> ${bat_1} </span>"
fi
st=$ft
echo $ft
echo $st

##-- interactive options -----------------------------------------------------------------
##----------------------------------------------------------------------------------------
case $BLOCK_BUTTON in
    1|2|3|4|5)
    ;;
esac

##-- EOF
