#!/usr/bin/env zsh
##----------------------------------------------------------------------------------------
##--     file: ${XDG_CONFIG_HOME}/dotfiles/i3/blocks/brightness                         --
##--      vim: set rnu nu ai et ts=4 sw=4 ft=zsh syn=zsh :                              --
##-- requires: xorg-xbacklight pango                                                    --
##----------------------------------------------------------------------------------------
##-- BOF

##-- draw the blocklet -------------------------------------------------------------------
##----------------------------------------------------------------------------------------
##-- variables
perc=`/usr/bin/xbacklight -get | awk '{print int($1+0.5)}'`
icon='✲'
#icon='☀'
#icon=''

##-- colours
bg0="#000000"
fg0="#dddd00"
fg1="#aaaaaa"

##-- full_text && short_text
ft="<span foreground='$fg0' background='$bg0'>${icon} </span>"
ft+="<span foreground='$fg1' background='$bg0'> ${perc}% </span>"
st=$ft
echo $ft
echo $st

##-- interactive options -----------------------------------------------------------------
##----------------------------------------------------------------------------------------
case $BLOCK_BUTTON in
    1|2|3|4|5)
    ;;
esac

##-- EOF
