#!/usr/bin/env zsh
##----------------------------------------------------------------------------------------
##--     file: ${XDG_CONFIG_HOME}/dotfiles/i3/blocks/date                               --
##--      vim: set rnu nu ai et ts=4 sw=4 ft=zsh syn=zsh :                              --
##-- requires: pango                                                                    --
##----------------------------------------------------------------------------------------
##-- BOF

##-- draw the blocklet -------------------------------------------------------------------
##----------------------------------------------------------------------------------------
##-- variables
datel=$(date +"%_A, %_d %_B %_Y")
dates=$(date +"%_a, %_d %_b %_y")
icon=""

##-- colours
bg0="#000000"
fg0="#26cece"
fg1="#aaaaaa"

##-- full_text && short_text
ft="<span foreground='$fg0' background='$bg0'> ${icon}  </span>"
ft+="<span foreground='$fg1' background='$bg0'> ${dates} </span>"
st=$ft
echo $ft
echo $st

##-- interactive options -----------------------------------------------------------------
##----------------------------------------------------------------------------------------
case $BLOCK_BUTTON in
    1|2|3|4|5)
    ;;
esac

##-- EOF
