#!/usr/bin/env zsh
##----------------------------------------------------------------------------------------
##--     file: ${XDG_CONFIG_HOME}/dotfiles/i3/blocks/mpd_stat                           --
##--      vim: set rnu nu ai et ts=4 sw=4 ft=zsh syn=zsh :                              --
##-- requires: pango mpc                                                                --
##----------------------------------------------------------------------------------------
##-- BOF

##-- draw the blocklet -------------------------------------------------------------------
##----------------------------------------------------------------------------------------
##-- variables
stat=`mpc | awk 'FNR==2 {print $1}' | sed 's|[^a-z^A-Z]||g'`
#icon=''
icon=''

##-- colours
bg0='#000000'
fg0='#3399bb'

##-- full_text && short_text
ft+="<span foreground='$fg0' background='$bg0'> ${icon} </span>"
st=$ft
echo $ft
echo $st

##-- interactive options -----------------------------------------------------------------
##----------------------------------------------------------------------------------------
case $BLOCK_BUTTON in
    1|2|3)
        mpc toggle
    ;;
esac

##-- EOF
