#!/usr/bin/env zsh
##----------------------------------------------------------------------------------------
##--     file: ${XDG_CONFIG_HOME}/dotfiles/i3/blocks/block                              --
##--      vim: set rnu nu ai et ts=4 sw=4 ft=zsh syn=zsh :                              --
##-- requires: pango                                                                    --
##----------------------------------------------------------------------------------------
##-- BOF

##-- draw the blocklet -------------------------------------------------------------------
##----------------------------------------------------------------------------------------
##-- variables
icon=""

##-- colours
fg0="#000000"
bg0="#1e1e1e"
fg1="#1e1e1e"
bg1="#000000"

##-- full_text && short_text
ft="<span foreground='$fg0' background='$bg0'>${icon} </span>"
ft+="<span foreground='$fg1' background='$bg1'>${icon}</span>"
st=$ft
echo $ft
echo $st

##-- interactive options -----------------------------------------------------------------
##----------------------------------------------------------------------------------------
case $BLOCK_BUTTON in
    1|2|3|4|5)
    ;;
esac

##-- EOF
